# =============================================================
#  PYNQ-Z2 constraints for image_control
#  Bank 35 = 3.3V (MIO / Arduino header)
#  Bank 34 = 3.3V (Raspberry Pi / ChipKit header)
# =============================================================

# ---- Clock (125 MHz onboard clock) --------------------------
set_property PACKAGE_PIN H16    [get_ports axi_clk]
set_property IOSTANDARD  LVCMOS33 [get_ports axi_clk]
create_clock -period 8.000 -name axi_clk [get_ports axi_clk]

# ---- Reset (active-low, mapped to BTN0) ---------------------
set_property PACKAGE_PIN D19    [get_ports axi_rst_n]
set_property IOSTANDARD  LVCMOS33 [get_ports axi_rst_n]

# ---- i_pixbuf[7:0] (Arduino D0-D7) -------------------------
set_property PACKAGE_PIN T14    [get_ports {i_pixbuf[0]}]
set_property PACKAGE_PIN U12    [get_ports {i_pixbuf[1]}]
set_property PACKAGE_PIN U13    [get_ports {i_pixbuf[2]}]
set_property PACKAGE_PIN V13    [get_ports {i_pixbuf[3]}]
set_property PACKAGE_PIN V15    [get_ports {i_pixbuf[4]}]
set_property PACKAGE_PIN T15    [get_ports {i_pixbuf[5]}]
set_property PACKAGE_PIN R16    [get_ports {i_pixbuf[6]}]
set_property PACKAGE_PIN U17    [get_ports {i_pixbuf[7]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {i_pixbuf[*]}]

# ---- i_pixbuf_valid (Arduino D8) ----------------------------
set_property PACKAGE_PIN V17    [get_ports i_pixbuf_valid]
set_property IOSTANDARD  LVCMOS33 [get_ports i_pixbuf_valid]

# ---- o_pixbuf[71:0] (Raspberry Pi GPIO) ---------------------
# RPi header gives you plenty of pins for the wide 72-bit bus
set_property PACKAGE_PIN W18    [get_ports {o_pixbuf[0]}]
set_property PACKAGE_PIN W19    [get_ports {o_pixbuf[1]}]
set_property PACKAGE_PIN Y18    [get_ports {o_pixbuf[2]}]
set_property PACKAGE_PIN Y19    [get_ports {o_pixbuf[3]}]
set_property PACKAGE_PIN W20    [get_ports {o_pixbuf[4]}]
set_property PACKAGE_PIN W21    [get_ports {o_pixbuf[5]}]
set_property PACKAGE_PIN Y21    [get_ports {o_pixbuf[6]}]
set_property PACKAGE_PIN Y22    [get_ports {o_pixbuf[7]}]
set_property PACKAGE_PIN V20    [get_ports {o_pixbuf[8]}]
set_property PACKAGE_PIN V22    [get_ports {o_pixbuf[9]}]
set_property PACKAGE_PIN U20    [get_ports {o_pixbuf[10]}]
set_property PACKAGE_PIN U22    [get_ports {o_pixbuf[11]}]
set_property PACKAGE_PIN T20    [get_ports {o_pixbuf[12]}]
set_property PACKAGE_PIN T22    [get_ports {o_pixbuf[13]}]
set_property PACKAGE_PIN T21    [get_ports {o_pixbuf[14]}]
set_property PACKAGE_PIN R22    [get_ports {o_pixbuf[15]}]
set_property PACKAGE_PIN P20    [get_ports {o_pixbuf[16]}]
set_property PACKAGE_PIN P22    [get_ports {o_pixbuf[17]}]
set_property PACKAGE_PIN N20    [get_ports {o_pixbuf[18]}]
set_property PACKAGE_PIN N22    [get_ports {o_pixbuf[19]}]
set_property PACKAGE_PIN M21    [get_ports {o_pixbuf[20]}]
set_property PACKAGE_PIN M22    [get_ports {o_pixbuf[21]}]
set_property PACKAGE_PIN L21    [get_ports {o_pixbuf[22]}]
set_property PACKAGE_PIN L22    [get_ports {o_pixbuf[23]}]
set_property PACKAGE_PIN K21    [get_ports {o_pixbuf[24]}]
set_property PACKAGE_PIN K22    [get_ports {o_pixbuf[25]}]
set_property PACKAGE_PIN J21    [get_ports {o_pixbuf[26]}]
set_property PACKAGE_PIN J22    [get_ports {o_pixbuf[27]}]
set_property PACKAGE_PIN H20    [get_ports {o_pixbuf[28]}]
set_property PACKAGE_PIN H22    [get_ports {o_pixbuf[29]}]
set_property PACKAGE_PIN G20    [get_ports {o_pixbuf[30]}]
set_property PACKAGE_PIN G22    [get_ports {o_pixbuf[31]}]
set_property PACKAGE_PIN F20    [get_ports {o_pixbuf[32]}]
set_property PACKAGE_PIN F22    [get_ports {o_pixbuf[33]}]
set_property PACKAGE_PIN E20    [get_ports {o_pixbuf[34]}]
set_property PACKAGE_PIN E22    [get_ports {o_pixbuf[35]}]
set_property PACKAGE_PIN D20    [get_ports {o_pixbuf[36]}]
set_property PACKAGE_PIN D22    [get_ports {o_pixbuf[37]}]
set_property PACKAGE_PIN C20    [get_ports {o_pixbuf[38]}]
set_property PACKAGE_PIN C22    [get_ports {o_pixbuf[39]}]
set_property PACKAGE_PIN B20    [get_ports {o_pixbuf[40]}]
set_property PACKAGE_PIN B22    [get_ports {o_pixbuf[41]}]
set_property PACKAGE_PIN A20    [get_ports {o_pixbuf[42]}]
set_property PACKAGE_PIN A22    [get_ports {o_pixbuf[43]}]
set_property PACKAGE_PIN B19    [get_ports {o_pixbuf[44]}]
set_property PACKAGE_PIN B21    [get_ports {o_pixbuf[45]}]
set_property PACKAGE_PIN A19    [get_ports {o_pixbuf[46]}]
set_property PACKAGE_PIN A21    [get_ports {o_pixbuf[47]}]
set_property PACKAGE_PIN C19    [get_ports {o_pixbuf[48]}]
set_property PACKAGE_PIN D21    [get_ports {o_pixbuf[49]}]
set_property PACKAGE_PIN E19    [get_ports {o_pixbuf[50]}]
set_property PACKAGE_PIN E21    [get_ports {o_pixbuf[51]}]
set_property PACKAGE_PIN F19    [get_ports {o_pixbuf[52]}]
set_property PACKAGE_PIN F21    [get_ports {o_pixbuf[53]}]
set_property PACKAGE_PIN G19    [get_ports {o_pixbuf[54]}]
set_property PACKAGE_PIN G21    [get_ports {o_pixbuf[55]}]
set_property PACKAGE_PIN H19    [get_ports {o_pixbuf[56]}]
set_property PACKAGE_PIN H21    [get_ports {o_pixbuf[57]}]
set_property PACKAGE_PIN J19    [get_ports {o_pixbuf[58]}]
set_property PACKAGE_PIN J20    [get_ports {o_pixbuf[59]}]
set_property PACKAGE_PIN K19    [get_ports {o_pixbuf[60]}]
set_property PACKAGE_PIN K20    [get_ports {o_pixbuf[61]}]
set_property PACKAGE_PIN L19    [get_ports {o_pixbuf[62]}]
set_property PACKAGE_PIN L20    [get_ports {o_pixbuf[63]}]
set_property PACKAGE_PIN M19    [get_ports {o_pixbuf[64]}]
set_property PACKAGE_PIN M20    [get_ports {o_pixbuf[65]}]
set_property PACKAGE_PIN N19    [get_ports {o_pixbuf[66]}]
set_property PACKAGE_PIN P19    [get_ports {o_pixbuf[67]}]
set_property PACKAGE_PIN R19    [get_ports {o_pixbuf[68]}]
set_property PACKAGE_PIN T19    [get_ports {o_pixbuf[69]}]
set_property PACKAGE_PIN U19    [get_ports {o_pixbuf[70]}]
set_property PACKAGE_PIN V18    [get_ports {o_pixbuf[71]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {o_pixbuf[*]}]

# ---- o_pixbuf_valid (Arduino D9) ----------------------------
set_property PACKAGE_PIN U18    [get_ports o_pixbuf_valid]
set_property IOSTANDARD  LVCMOS33 [get_ports o_pixbuf_valid]

# ---- o_intr (Arduino D10) -----------------------------------
set_property PACKAGE_PIN T16    [get_ports o_intr]
set_property IOSTANDARD  LVCMOS33 [get_ports o_intr]